language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: 1.0  
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("PermPlain")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
